import { Game } from './types';

export const GAMES: Game[] = [
  { id: 'scvi', name: 'Scarlatto / Violetto', baseOdds: 4096, pokedex: 'paldea', maxNationalId: 1025 },
  { id: 'la', name: 'Leggende: Arceus', baseOdds: 4096, pokedex: 'hisui', maxNationalId: 905 },
  { id: 'bdsp', name: 'Diamante Lucente / Perla Splendente', baseOdds: 4096, pokedex: 'extended-sinnoh', maxNationalId: 493 },
  { id: 'swsh', name: 'Spada / Scudo', baseOdds: 4096, pokedex: 'galar', maxNationalId: 898 },
  { id: 'lgpe', name: 'Let\'s Go Pikachu / Eevee', baseOdds: 4096, pokedex: 'letsgo-kanto', maxNationalId: 153 },
  { id: 'usum', name: 'Ultrasole / Ultraluna', baseOdds: 4096, pokedex: 'updated-alola', maxNationalId: 807 },
  { id: 'sm', name: 'Sole / Luna', baseOdds: 4096, pokedex: 'original-alola', maxNationalId: 802 },
  { id: 'oras', name: 'Rubino Omega / Zaffiro Alpha', baseOdds: 4096, pokedex: 'updated-hoenn', maxNationalId: 721 },
  { id: 'xy', name: 'X / Y', baseOdds: 4096, pokedex: 'kalos-central', maxNationalId: 721 },
  { id: 'b2w2', name: 'Bianco 2 / Nero 2', baseOdds: 8192, pokedex: 'updated-unova', maxNationalId: 649 },
  { id: 'bw', name: 'Bianco / Nero', baseOdds: 8192, pokedex: 'original-unova', maxNationalId: 649 },
  { id: 'hgss', name: 'HeartGold / SoulSilver', baseOdds: 8192, pokedex: 'updated-johto', maxNationalId: 493 },
  { id: 'pt', name: 'Platino', baseOdds: 8192, pokedex: 'extended-sinnoh', maxNationalId: 493 },
  { id: 'dp', name: 'Diamante / Perla', baseOdds: 8192, pokedex: 'original-sinnoh', maxNationalId: 493 },
  { id: 'em', name: 'Smeraldo', baseOdds: 8192, pokedex: 'hoenn', maxNationalId: 386 },
  { id: 'frlg', name: 'Rosso Fuoco / Verde Foglia', baseOdds: 8192, pokedex: 'kanto', maxNationalId: 386 },
  { id: 'rs', name: 'Rubino / Zaffiro', baseOdds: 8192, pokedex: 'hoenn', maxNationalId: 386 },
  { id: 'c', name: 'Cristallo', baseOdds: 8192, pokedex: 'original-johto', maxNationalId: 251 },
  { id: 'gs', name: 'Oro / Argento', baseOdds: 8192, pokedex: 'original-johto', maxNationalId: 251 },
  { id: 'y', name: 'Giallo', baseOdds: 8192, pokedex: 'kanto', maxNationalId: 151 },
  { id: 'rb', name: 'Rosso / Blu', baseOdds: 8192, pokedex: 'kanto', maxNationalId: 151 },
];
